language: python
sudo: false

addons:
  apt:
    packages:
    - libphysfs-dev

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"
  - LUA="luajit=2.0" CARBON="YES"
  - LUA="luajit=2.1" CARBON="YES"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH="$PATH:$PWD/lua_install/bin"
  - export LD_LIBRARY_PATH="$PWD/lua_install/lib:/usr/lib:/lib"
  - ./scripts/travis-carbon-setup.sh $CARBON

install:
  - luarocks install luasocket
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - busted --verbose --coverage spec

after_success:
  - luacov-coveralls -e $TRAVIS_BUILD_DIR/lua_install
